apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: frogs.amphibians.animals.com
spec:
  preserveUnknownFields: false
  group: amphibians.animals.com
  names:
    kind: Frog
    listKind: FrogList
    plural: frogs
    singular: frog
  scope: Namespaced
  versions:
    - name: v3
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            apiVersion:
              description: 'APIVersion defines the versioned schema of this representation of an object'
              pattern: amphibians.animals.com/v3
              type: string
            kind:
              enum:
                - Frog
                - FrogList
              type: string
              description: 'Kind is a string value representing the REST resource this object represents'
            metadata:
              type: object
            spec:
              type: object
              description: The schema for Frog
              properties:

                characteristics:
                  type: array
                  properties:
                    color:
                      type: string
                    age:
                      type: integer
                    other:
                      type: object
                      properties:
                        firstName:
                          type: string
                          pattern: "^k"
                  items:
                    type: object
                    oneOf:
                      - properties:
                          color:
                            example: blue
                      - properties:
                          age:
                            example: 2
                      - properties:
                          other:
                            properties:
                              firstName:
                                example: kermit
