apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: frogs.amphibians.animals.com
spec:
  preserveUnknownFields: false
  group: amphibians.animals.com
  names:
    kind: Frog
    listKind: FrogList
    plural: frogs
    singular: frog
  scope: Namespaced
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            apiVersion:
              description: 'APIVersion defines the versioned schema of this representation of an object'
              pattern: amphibians.animals.com/v1
              type: string
            kind:
              enum:
                - Frog
                - FrogList
              type: string
              description: 'Kind is a string value representing the REST resource this object represents'
            metadata:
              type: object
            spec:
              type: object
              description: The schema for Frog
              properties:
                prey:
                  type: array
                  items:
                    type: object
                    properties:
                      cricket:
                        type: object
                        properties:
                          name:
                            type: string
                          color:
                            type: string
                      fly:
                        type: object
                        properties:
                          name:
                            type: string
                          size:
                            type: string

