apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: frogs.amphibians.animals.com
spec:
  preserveUnknownFields: false
  group: amphibians.animals.com
  names:
    kind: Frog
    listKind: FrogList
    plural: frogs
    singular: frog
  scope: Namespaced
  versions:
    - name: v4
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            apiVersion:
              description: 'APIVersion defines the versioned schema of this representation of an object'
              pattern: amphibians.animals.com/v4
              type: string
            kind:
              enum:
                - Frog
                - FrogList
              type: string
              description: 'Kind is a string value representing the REST resource this object represents'
            metadata:
              type: object
            spec:
              type: object
              description: The schema for Frog
              properties:

                characteristics:
                  type: array
                  items:
                    type: object
                    properties:
                      prop1a:
                        type: string
                        pattern: "^a"
                      prop1b:
                        type: string
                      prop2a:
                        type: string
                      prop2b:
                        type: string
                      prop3:
                        type: object
                        properties:
                          prop1:
                            type: object
                            required:
                              - prop1a
                              - prop1b
                            properties:
                              prop1a:
                                type: string
                              prop1b:
                                type: string
                          prop2:
                            type: object
                            properties:
                              prop2a:
                                type: string
                              prop2b:
                                type: string
                    allOf:

                      # - properties:
                      #     prop1:
                      #       example: 'object'
                      # - properties:
                      #     prop2:
                      #       example: 'object'

                      - properties:
                          prop3:
                            example: 'object'

