apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: rabbits.mammals.animals.com
spec:
  preserveUnknownFields: false
  group: mammals.animals.com
  names:
    kind: Rabbit
    listKind: RabbitList
    plural: rabbits
    singular: rabbit
  scope: Namespaced
  versions:

    - name: v1
      served: true
      storage: false
      additionalPrinterColumns:
        - name: Kind
          type: string
          description: Custom resource kind
          jsonPath: .kind
        - name: state
          description: Custom resource state
          type: string
          jsonPath: .status.state
        - name: age
          description: Creation time
          type: date
          jsonPath: .metadata.creationTimestamp
      schema:
        openAPIV3Schema:
          type: object
          properties:
            apiVersion:
              pattern: mammals.animals.com/v1
              type: string
            kind:
              enum:
                - Rabbit
                - RabbitList
              type: string
            metadata:
              type: object
            spec:
              type: object
              required:
                - v1name
                - v1age
              description: The schema for Rabbit
              properties:
                v1name:
                  type: string
                v1age:
                  type: integer
                  minimum: 1

    - name: v2
      served: true
      storage: true
      additionalPrinterColumns:
        - name: Kind
          type: string
          description: Custom resource kind
          jsonPath: .kind
        - name: state
          description: Custom resource state
          type: string
          jsonPath: .status.state
        - name: age
          description: Creation time
          type: date
          jsonPath: .metadata.creationTimestamp
      schema:
        openAPIV3Schema:
          type: object
          properties:
            apiVersion:
              pattern: mammals.animals.com/v2
              type: string
            kind:
              enum:
                - Rabbit
                - RabbitList
              type: string
            metadata:
              type: object
            spec:
              type: object
              required:
                - v1name
                - v1age
                - v2color
              description: The schema for Rabbit
              properties:
                v1name:
                  type: string
                v1age:
                  type: integer
                  minimum: 1
                v2color:
                  type: string
